
name: Build alpha package

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Alpha Package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      PACKAGE_PATH: artifacts

    steps:
      - name: Clone repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Create NuGet package
        run: >
          dotnet pack
          --configuration Release
          --no-build
          --no-restore
          --output ${{ env.PACKAGE_PATH }}
          --version-suffix alpha-build$GITHUB_RUN_NUMBER
          -property:RepositoryCommit=$GITHUB_SHA

      - name: NuGet login
        uses: nuget/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to NuGet
        run: >
          dotnet nuget
          push ${{ env.PACKAGE_PATH }}/*
          --api-key "${{ steps.login.outputs.NUGET_API_KEY }}"
          --source https://api.nuget.org/v3/index.json

